name: 叮咚买菜助手
addr: :9999 # web服务端口号 多开需修改为其他端口号
meituan:
  station: 10000192
  monitor_needed: true
  monitor_success_wait: 10
  notify_needed: true
dingdong:
  base_concurrency: 1 # 除了提交订单的其他请求并发数, 默认为1
  submit_concurrency: 2 # 最后提交订单的并发数, 默认为2
  snap_up: 0 # 抢购, 0 关闭, 1 六点抢, 2 八点半抢, 3 六点和八点半都抢
  advance_time: 20 # 抢购提前进入时间, 单位:秒, 默认为20秒
  pick_up_needed: false # 闲时捡漏开关, false 关闭, true 打开, 在抢购高峰期之外的时间捡漏
  monitor_needed: true # 监听开关, 监听是否有可运力
  monitor_success_wait: 10 # 成功监听(发起捡漏或通知)之后的休息时间, 单位:分钟, 默认为10分钟
  notify_needed: true # 通知开关, 发现运力时或捡漏成功时的通知, 使用需同时打开监听或捡漏
  audio_needed: true # 播放音频开关, 在订单提交成功后播放音频
  pay_type: 25 # 支付方式
  headers: # 请求头 用户可以自定义, 自由增加删除参数
    cookie:  # 填写自己抓包得到的 cookie
    user-agent: 'Mozilla/5.0 (iPhone; CPU iPhone OS 15_4_1 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Mobile/15E148 MicroMessenger/8.0.18(0x1800123f) NetType/WIFI Language/zh_CN'
    ddmc-app-client-id: 10
    ddmc-api-version: 9.50.2
    ddmc-build-version: 2.85.3
    ddmc-sdkversion: 0
    ddmc-channel: applet
  params: # 请求参数 用户可以自定义, 自由增加删除参数
  #  device_token: ''
bark: # Bark 用户组, 苹果使用 Bark 推送通知, 可以添加多个与你同属一个叮咚发货站点的用户
  - xxx # xxx 替换为你自己的 Bark token, 域名默认为"https://api.day.app", 如果你的域名不是默认的, 需要加上域名前缀
push_plus: # PushPlus 用户组, 安卓和苹果都可使用 PushPlus 通过微信通知, 可以添加多个与你同属一个叮咚发货站点的用户
  - xxx # xxx 替换为你自己的 PushPlus token
